version: '3'
services:
  db:
    image: neo4j
    ports:
     - "7474:7474"
     - "7473:7473"
     - "7687:7687"
    volumes:
      - ./neo4j/logs:/logs
      - ./neo4j/data:/data
  web:
    build: .
    # command: bundle exec rails s -p 3000 -b '0.0.0.0'
    command: bundle exec rdebug-ide --host 0.0.0.0 --port 1234 -- /budoka/bin/rails s -p 3000 -b '0.0.0.0'
    volumes:
      - .:/budoka
    ports:
      - "3000:3000"
      - "1234:1234"
    depends_on:
      - db
